### ISSUE TITLE
Use Iterable<String> classes instead of a String classAttributes

### ISSUE THREAD

**Issue by krillefear** [erlage/rad#10]
For HTML Widgets we can define classes in Rad by using the `classAttributes`. This maps to the `classNames` attribute of HtmlElements in dart:html. But in HtmlElements we also have the `classes` parameter where we can use an Iterable. By using a Set<String> there we have some advantages:

The list of class is easier to read. Especially when using tailwindCSS we will have much cleaner code.

Compare:

```dart
class EmptyView extends StatelessWidget {
  final String text;

  EmptyView({required this.text});

  @override
  Widget build(context) {
    return Division(
      classAttribute: 'w-full h-full justify-center items-center flex',
      children: [
        Division(
          classAttribute: 'p-4 text-center text-sm text-gray-600',
          innerText: text,
        )
      ],
    );
  }
}
```

To:

```dart
import 'dart:html';

import 'package:rad/rad.dart';
import 'package:rad/widgets_html.dart';

class EmptyView extends StatelessWidget {
  final String text;

  EmptyView({required this.text});

  @override
  Widget build(context) {
    return Division(
      classes: {
        'w-full',
        'h-full',
        'justify-center',
        'items-center',
        'flex',
      },
      children: [
        Division(
          classes: {
            'p-4',
            'text-center',
            'text-sm',
            'text-gray-600',
          },
          innerText: text,
        )
      ],
    );
  }
}

```

Also by using Sets we make sure that we can't pass the same class multiple times.

Proposal: We could replace `String classAttribute` with `Iterable<String> classes` or we add `classes` as an additional attribute and define what happens if the user uses both.

**Comment by erlage** [comment]
Using iterable does help in some cases but:

- Iterables are bit more verbose.
- Not-compaitable with HTML attributes. We're trying to stay close to HTML attributes where possible.
- Have negative performance implications(going to be very slow compares to string classes).

We could have a separate property `classes` but I think it'll make things unnecessarily complex. In general, having multiple ways to do the same thing pollutes API and makes things difficult to learn/maintain. I had already made few mistakes in the past regarding this, for example `child`/`innerText` properties of HTML widgets are redundant, and I'm looking to fix those mistakes before stable release pans out.

At some point in future, someone might want to add [conditional classes](https://github.com/JedWatson/classnames) too. So I think it's best deliver high-performant HTML widgets upon which one can easily build abstractions they want. For now, I can at least assure you that having duplicate classes in `classAttribute` won't cause any problems. Moreover, duplicates are going to be very rare.

**Comment by erlage** [comment]
> HtmlElement have the classes parameter and so I would expect that Widgets would have them as well

By 'compaitability with HTML attributes', I mean static HTML attributes which are present in static markup, those are the ones that we're trying to be more compatiable with. Things like `classes` are 'properties' that exists in the context of script running inside browser.

> I don't think that this would have such a bad impact on the performance 

<details>
<summary>If we consider performance</summary>
<p>

Best way would be to [benchmark it](https://measurethat.net/Benchmarks/Show/19794/0/rewrite-multiple-classes-classname-vs-setattribute-vs-c). I've tested it on firefox & chrome. On both browsers, `className` is the fastest while `classList` is the slowest method. I believe dart's `.classes` is going to be the worst as it's using a `LinkedHashSet` underneath not `classList`. Right now we're using `setAttribute` to set classes but transitiong to use `className` is easy as both `className` & `setAttribute` accept `String` argument.

Then there's one more thing, comparing two iterables is definitely slow compares to comparing two string literals so iterables are going to impact our diffing mechanism as well([1](https://github.com/erlage/rad/blob/489e5eb80001b9070a644c0fe30b7e1570e26236/packages/rad/lib/src/widgets/abstract/html_widget_base.dart#L122), [2](https://github.com/erlage/rad/blob/489e5eb80001b9070a644c0fe30b7e1570e26236/packages/rad/lib/src/widgets/abstract/html_widget_base.dart#L269)).

</p>
</details>

<details>
<summary>If we don't consider performance</summary>
<p>

Even if for a moment we assume that there won't any performance difference at all or let's assume `classes` is the fastest, then there's another prespective to it. See everyone has their own preference and given that `classAttribute` is the most commonly used property of HTML widgets, there will always going to be different opinions about it. I personally like to have it as String because it's easier to type while you/your-team would like to have it as iterable.

In situations like these, we can rely on experience of other frameworks. Rad has taken inspiration from Flutter & React, and in React people seem to have accepted strings in className instead of iterables. Just like people have in React, we can create work-arounds for this:

```dart
String classes(Set<String> classes) => classes.join(' ');

Span(
  classAttribute: classes({
    'w-full',
    'h-full',
    'justify-center',
    'items-center',
  }),
);
```
If above work-around is not enough and this is the only thing that's stopping you from using Rad, then we can generate a custom implementation of HTML widgets and publish it as a separate package and all you've to do is import `rad/widgets_custom_html` instead of `rad/widgets_html`.

</p>
</details>

**Comment by erlage** [comment]
Hi again! 

There are two updates on this issue,

1. `classAttribute` has been renamed to `className`.

2. A package generator has been added that you can use for generating custom HTML widgets. It's specifically built to address this issue so it allows customizing only class attribute for now.

Package generator usage:
```sh
# 1. clone repo

git clone https://github.com/erlage/rad
cd rad/tool/pkg-gen-html-widgets

# 2. Generate package

py gen.py --className:retype=set

# 3. Post generation tasks

cd out 
dart pub get & dart format .
```
Above steps will generate a ready to consume/deploy package containing HTML widgets in which className accepts `Set<String>` values. You can also generate a package with `List<String>` className, using `--className:retype=list`. Apart from type signature of className you can also change its name:
```sh
py gen.py \
  --className:retype=set \ 
  --className:rename=classes
```
There are some package specific options as well, [see tool/readme](https://github.com/erlage/rad/tree/main/tool#tool-pkg-gen-html-widgets).
