### ISSUE TITLE
this package use seo?

### ISSUE THREAD

**Issue by flexmeKim** [erlage/rad#2]
Hello, I happened to see this package. What does this package ultimately mean?
Is it possible to use seo by using the package?
Is it a better package than the seo_renderer package?
I want to develop the web with flutter, so I have a lot of questions!

**Comment by erlage** [comment]
Hey!

> What does this package ultimately mean?

This package is actually a web framework that's heavily inspired from Flutter framework. It can be used to create websites/web apps, just like any other web framework(React, Vue) but in more of a Flutter way.

> Is it possible to use seo by using the package?
> Is it a better package than the seo_renderer package?

With this framework, I'm trying to solve issues that I faced in Flutter web so it's kind of an alternative to Flutter web. **But** since this framework is a separate endeavour, you cannot use it to solve problems in your Flutter app. It's intended to be used standalone i.e without Flutter.

> I want to develop the web with flutter, so I have a lot of questions!

I'd love to help you out but unfortunately I can't answer Flutter related questions here. Consider asking your questions in Flutter discord/reddit:
- (r/FlutterDev) https://discord.gg/qwGsRT5hDr
- (r/FlutterDev) https://www.reddit.com/r/FlutterDev/
