### ISSUE TITLE
Extendability problem

### ISSUE THREAD

**Issue by vasil-boshnyakov** [erlage/rad#27]
Hello,

first of all thanks for the interesting and great project! :)

I want to use Bulma CSS in my hobby project. Bulma uses `section` as core element. I can't implement this:
```
class Section extends HTMLWidgetBase {
...
```

because `HTMLWidgetBase` is marked as `@internal`. The only way to add it is to copy the `Rad` source code and use it locally.

It will be great if (at least) `HTMLWidgetBase` is exposed to other packages. Thanks!

**Comment by hamsbrar** [comment]
Thanks for bringing this up.

#### Another issue:

To implement a widget that renders `section` element, we've to return `section` from [`correspondingTag`](https://github.com/erlage/rad/blob/506f1ff0f7b61822c6706aef2e6a9c2c5760f434/packages/rad/lib/src/widgets/abstract/widget.dart#L34). This is something we cannot do as we can return only a valid [`DomTagType`](https://github.com/erlage/rad/blob/506f1ff0f7b61822c6706aef2e6a9c2c5760f434/packages/rad/lib/src/core/common/enums.dart#L472) value from `correspondingTag` and there's no entry for `section` in the `DomTagType` enum.

In order to fix this we've to first add entry for `section` in the enum `DomTagType` and then you can:

- Option 1: Use `HTMLWidgetBase` (but like you said this requires making `HTMLWidgetBase` public).

- Option 2: Use a existing HTML widget (e.g [`span`](https://pub.dev/documentation/rad/latest/widgets_html/Span-class.html)).

  ```dart
  class Section extends Span {
    const Section({
      super.key,
      super.ref,
      super.id,
      super.title,
      super.style,
      super.className,
      super.hidden,
      super.innerText,
      super.child,
      super.children,
      super.onClick,
      super.additionalAttributes,
    }));

    @override
    DomTagType get correspondingTag => DomTagType.section; // important!
  }

  runApp(
    app: Section(innerText: 'hello'),  // <section> hello </section>
    appTargetId: 'out',
  );
  ```

#### On framework side:

Here's what I think we should do:

1. Add all the missing entries(not just `section`) to the enum `DomTagType`.
2. Add `Section` widget to framework HTML widgets(so that you don't have to implement it).
3. Maybe add `HTMLWidgetBase` to public API. I'm not sure whether we should do that. I mean its functionality is easily accessible(as shown in option-2) through any HTML widget(`span`, `div`, ...). But if you still want it, we can make it public. 

If you or anyone else would like to work on any specific part, please feel free to do so (but do let us know here so that I don't start working on the same thing).

**Comment by hamsbrar** [comment]
I've made all the changes, including adding missing entries, making `HTMLWidgetBase` public, and adding `Section` widget. 
 
 The new version ([v1.7.0](https://pub.dev/packages/rad/versions/1.7.0)) is live. Enjoy! 🚀
